export const CREATE_BUCKET_REQUEST = "CREATE_BUCKET_REQUEST";
export const CREATE_BUCKET_SUCCESS = "CREATE_BUCKET_SUCCESS";
export const CREATE_BUCKET_FAILURE = "CREATE_BUCKET_FAILURE";

export const GET_BUCKET_LIST_REQUEST = "GET_BUCKET_LIST_REQUEST";
export const GET_BUCKET_LIST_SUCCESS = "GET_BUCKET_LIST_SUCCESS";
export const GET_BUCKET_LIST_FAILURE = "GET_BUCKET_LIST_FAILURE";

export const UPDATE_BUCKET_LIST_REQUEST = "UPDATE_BUCKET_LIST_REQUEST";
export const UPDATE_BUCKET_LIST_SUCCESS = "UPDATE_BUCKET_LIST_SUCCESS";
export const UPDATE_BUCKET_LIST_FAILURE = "UPDATE_BUCKET_LIST_FAILURE";

export const DELETE_BUCKET_LIST_REQUEST = "DELETE_BUCKET_LIST_REQUEST";
export const DELETE_BUCKET_LIST_SUCCESS = "DELETE_BUCKET_LIST_SUCCESS";
export const DELETE_BUCKET_LIST_FAILURE = "DELETE_BUCKET_LIST_FAILURE";

export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";
