export const CREATE_BUCKET_REQUEST = "CREATE_BUCKET_REQUEST";
export const CREATE_BUCKET_SUCCESS = "CREATE_BUCKET_SUCCESS";
export const CREATE_BUCKET_FAILURE = "CREATE_BUCKET_FAILURE";

export const GET_BUCKET_LIST_REQUEST = "GET_BUCKET_LIST_REQUEST";
export const GET_BUCKET_LIST_SUCCESS = "GET_BUCKET_LIST_SUCCESS";
export const GET_BUCKET_LIST_FAILURE = "GET_BUCKET_LIST_FAILURE";
